Разобраться с бинарными данными

In [64]:
import pandas as pd
import struct
import numpy as np
import os

In [65]:
test_file_path = "D:\\TestJupyter\\data\\Stud_IT_2025_Module_2\\binary_data_train\\0\\img_000001_label_0.mybin"
with open(test_file_path, 'rb') as raw_data:
    read_data_head = raw_data.read(12)
    bin_data = raw_data.read()

In [66]:
# 4 char 4 uint32 1 uint8 1 uint8 2 byte
unpacked_head = struct.unpack('4s i B B h', read_data_head)
unpacked_head

(b'NMPY', 784, 1, 0, 0)

In [104]:
#head_struct = struct.Struct('4s i B B h')
def unpacking_row(path, i):
    with open(path, 'rb') as raw_data:
        read_head = raw_data.read(12)
        read_bin_data = raw_data.read()
        #unpacked_head = head_struct.unpack(read_head)
        bin_data = np.frombuffer(read_bin_data, dtype = np.uint8)
        row = {
            'Label' : i,
            #'Type' : unpacked_head[0],
            #'Amount' : unpacked_head[1],
            #'Version' : unpacked_head[2],
            #'Encoding' : unpacked_head[3],
            'Data' : bin_data
        }
        return row

In [105]:
unpacking_row(test_file_path, 0)

{'Label': 0,
 'Data': array([ 38,  42,  46,  49,  50,  45,  37,  27,  25,  33,  51,  60,  62,
         57,  51,  49,  43,  40,  37,  45,  50,  54,  49,  45,  41,  35,
         27,  18,  46,  51,  55,  55,  53,  48,  42,  35,  33,  37,  50,
         57,  58,  53,  49,  50,  49,  51,  46,  47,  43,  41,  35,  32,
         29,  25,  19,  13,  53,  60,  63,  59,  53,  48,  45,  42,  42,
         43,  49,  54,  55,  54,  53,  59,  67,  73,  68,  55,  38,  27,
         19,  17,  16,  14,  10,   7,  48,  54,  57,  52,  45,  41,  41,
         41,  41,  40,  44,  50,  55,  62,  69,  83,  98, 109, 102,  77,
         47,  24,  13,  11,  11,  10,   6,   3,  35,  39,  40,  36,  33,
         30,  30,  30,  31,  31,  35,  44,  57,  75,  95, 118, 140, 150,
        140, 107,  66,  33,  17,  14,  14,  12,   6,   3,  25,  25,  23,
         20,  19,  19,  19,  19,  19,  20,  26,  41,  63,  94, 127, 157,
        180, 186, 173, 138,  93,  53,  29,  20,  17,  14,   7,   3,  29,
         25,  18,  12,  10,  10,  11,  13,  14,  19,  28,  47,  78, 119,
        159, 189, 206, 205, 191, 161, 121,  78,  46,  27,  18,  13,   6,
          3,  48,  38,  24,  11,   5,   5,   9,  14,  20,  29,  43,  67,
        103, 143, 180, 203, 211, 203, 191, 173, 146, 108,  68,  37,  17,
          8,   3,   1,  64,  51,  33,  15,   5,   3,   8,  18,  31,  48,
         69,  94, 123, 153, 178, 190, 190, 180, 174, 171, 161, 134,  91,
         50,  20,   7,   1,   0,  71,  58,  39,  18,   6,   3,   9,  23,
         45,  72,  98, 117, 131, 140, 149, 151, 149, 141, 142, 153, 160,
        147, 108,  61,  24,   7,   1,   0,  67,  56,  38,  19,   6,   3,
         11,  30,  60,  95, 121, 129, 123, 111, 105, 102, 101,  99, 107,
        127, 147, 145, 114,  67,  27,   7,   1,   0,  61,  50,  34,  17,
          6,   5,  18,  43,  80, 115, 133, 126, 103,  78,  64,  59,  61,
         67,  79, 103, 128, 135, 112,  69,  29,   8,   1,   0,  54,  43,
         27,  13,   6,  12,  32,  63, 101, 126, 128, 108,  80,  53,  38,
         33,  38,  48,  64,  90, 117, 129, 110,  70,  32,  10,   2,   0,
         48,  36,  20,   9,   8,  22,  51,  87, 118, 125, 109,  81,  56,
         37,  26,  23,  28,  41,  60,  88, 117, 130, 113,  75,  37,  14,
          4,   1,  44,  32,  17,   9,  14,  36,  72, 107, 126, 114,  85,
         55,  36,  25,  20,  18,  25,  40,  64,  95, 124, 133, 114,  79,
         43,  21,   9,   4,  44,  32,  18,  12,  23,  50,  89, 118, 123,
         98,  62,  34,  22,  16,  16,  18,  29,  48,  76, 107, 128, 128,
        104,  72,  44,  26,  14,   7,  45,  35,  24,  20,  34,  65, 102,
        124, 119,  87,  50,  24,  14,  12,  14,  22,  38,  63,  91, 115,
        122, 109,  82,  57,  40,  28,  18,  11,  46,  39,  32,  31,  47,
         76, 111, 129, 121,  87,  51,  28,  19,  18,  23,  35,  56,  83,
        104, 113, 103,  80,  53,  35,  28,  23,  17,  11,  42,  40,  39,
         42,  59,  85, 118, 137, 133, 105,  72,  49,  40,  41,  46,  58,
         77,  96, 105,  98,  76,  49,  28,  18,  17,  16,  13,   9,  39,
         39,  42,  49,  66,  90, 122, 144, 149, 130, 104,  83,  74,  75,
         80,  87,  96, 101,  95,  76,  49,  26,  11,   7,   7,   7,   6,
          4,  40,  39,  41,  47,  64,  88, 119, 145, 158, 150, 131, 114,
        105, 105, 107, 108, 105,  98,  82,  58,  31,  13,   4,   3,   3,
          3,   3,   1,  40,  37,  35,  39,  53,  76, 107, 135, 150, 149,
        137, 125, 118, 118, 116, 110, 102,  91,  72,  48,  24,  10,   4,
          4,   4,   4,   3,   1,  37,  36,  34,  35,  42,  61,  88, 113,
        126, 125, 116, 108, 105, 103,  99,  92,  86,  79,  66,  44,  23,
         13,  10,  12,  13,  12,   9,   5,  28,  32,  34,  36,  38,  50,
         67,  83,  90,  85,  77,  74,  76,  76,  73,  66,  65,  63,  55,
         40,  25,  20,  22,  28,  31,  30,  22,  15,  22,  30,  38,  43,
         43,  46,  50,  54,  52,  46,  39,  39,  44,  46,  47,  43,  44,
         45,  43,  34,  25,  24,  31,  43,  51,  50,  38,  27,  15,  23,
         33,  41,  42,  40,  35,  29,  23,  18,  15,  16,  23,  28,  33,
         30,  31,  30,  31,  27,  24,  25,  34,  52,  66,  67,  53,  40,
         10,  17,  25,  33,  34,  31,  22,  14,   8,   4,   4,   5,  11,
         17,  24,  24,  24,  22,  24,  23,  21,  21,  30,  49,  66,  70,
         58,  44,   6,  11,  16,  22,  23,  21,  14,   6,   2,   0,   1,
          1,   6,  12,  21,  22,  22,  19,  21,  21,  19,  17,  24,  43,
         61,  67,  58,  46], dtype=uint8)}

In [106]:
path = "D:\\TestJupyter\\data\\Stud_IT_2025_Module_2\\binary_data_train"

In [107]:
data_list = []
for i in range(0, 10):
    dir_path = path+f'\\{i}'
    file_names = os.listdir(dir_path)
    for file in file_names:
        file_path = dir_path + '\\' + file
        row = unpacking_row(file_path, i)
        data_list.append(row)
df = pd.DataFrame(data_list)

In [108]:
df.head()

   Label                                               Data
0      0  [38, 42, 46, 49, 50, 45, 37, 27, 25, 33, 51, 6...
1      0  [39, 28, 13, 5, 5, 14, 24, 40, 50, 55, 50, 41,...
2      0  [6, 14, 23, 34, 35, 34, 34, 42, 43, 38, 25, 17...
3      0  [6, 9, 19, 37, 50, 51, 41, 30, 27, 31, 37, 40,...
4      0  [0, 0, 0, 0, 0, 0, 0, 2, 4, 9, 9, 9, 4, 2, 1, ...

In [109]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   50000 non-null  int64
 1   Data    50000 non-null  object
dtypes: int64(1), object(1)
memory usage: 781.4+ KB

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
def count_plot(column, title):
    plt.figure(figsize=(10, 6))
    sns.countplot(x=column, data = df, hue=column)
    plt.title(title)
    plt.show()

In [122]:
X = np.stack(df['Data'])
y = df['Label']

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [125]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [126]:
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', None)
])

In [127]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [119]:
param_grid = [
    {
        'classifier': [
            RandomForestClassifier(
            random_state=42, 
            class_weight='balanced'
        )],
        'classifier__n_estimators': [50, 100, 200, 400],
        'classifier__max_depth': [None, 5, 10, 20]
    },
    {
        'classifier': [DecisionTreeClassifier(random_state=42)],
        'classifier__criterion': ['gini', 'entropy', 'log_loss'],
        'classifier__splitter': ['best', 'random'],
        'classifier__max_depth': [None, 5, 10],
        'classifier__max_features': [ None, 'sqrt', 'log2']
    }
]

In [135]:
param_grid = [
    {
        'classifier': [RandomForestClassifier(random_state=42, class_weight='balanced', n_jobs=-1)],
        'classifier__n_estimators': [50, 100, 200, 400],
          # Проверьте сначала одно дефолтное значение
        'classifier__max_depth': [20]
    },
]

In [136]:
grid = GridSearchCV(pipe, param_grid, cv=5, scoring='accuracy', n_jobs=-1)

In [137]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             n_jobs=-1,
             param_grid=[{'classifier': [RandomForestClassifier(class_weight='balanced',
                                                                n_jobs=-1,
                                                                random_state=42)],
                          'classifier__max_depth': [20],
                          'classifier__n_estimators': [50, 100, 200, 400]}],
             scoring='accuracy')

In [138]:
from sklearn.metrics import accuracy_score, classification_report

In [139]:
print(f"Победитель: {grid.best_params_}")
print(f"Лучший средний CV-score: {grid.best_score_:.4f}")
best_pipeline = grid.best_estimator_
final_preds = best_pipeline.predict(X_test)
print(f"Финальный Accuracy на тесте: {accuracy_score(y_test, final_preds):.4f} /n {classification_report(y_test, final_preds)}")

Победитель: {'classifier': RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42), 'classifier__max_depth': 20, 'classifier__n_estimators': 400}
Лучший средний CV-score: 0.9172
Финальный Accuracy на тесте: 0.9230 /n               precision    recall  f1-score   support

           0       0.97      0.98      0.97      1219
           1       0.94      0.98      0.96      1458
           2       0.94      0.93      0.94      1268
           3       0.93      0.89      0.90      1236
           4       0.92      0.90      0.91      1220
           5       0.91      0.91      0.91      1131
           6       0.95      0.96      0.96      1229
           7       0.92      0.91      0.92      1291
           8       0.90      0.87      0.88      1212
           9       0.84      0.90      0.87      1236

    accuracy                           0.92     12500
   macro avg       0.92      0.92      0.92     12500
weighted avg       0.92      0.92      0.92     12500

In [140]:
model = best_pipeline

In [141]:
test_path = "D:\\TestJupyter\\data\\Stud_IT_2025_Module_2\\binary_data_test"

In [151]:
test_data_list = []
test_dir_path = test_path
test_file_names = os.listdir(test_dir_path)
i = 50000
for file in test_file_names:
    
    test_file_path = test_dir_path + '\\' + file
    test_row = unpacking_row(test_file_path, i)
    test_data_list.append(test_row)
    i += 1
test_df = pd.DataFrame(test_data_list)

In [152]:
test_df

      Label                                               Data
0     50000  [1, 6, 19, 41, 58, 62, 55, 50, 53, 63, 65, 63,...
1     50001  [53, 61, 70, 69, 63, 49, 36, 27, 24, 27, 25, 2...
2     50002  [75, 66, 50, 31, 25, 27, 40, 55, 64, 59, 41, 2...
3     50003  [39, 29, 17, 12, 18, 33, 54, 68, 62, 48, 33, 3...
4     50004  [5, 8, 14, 20, 27, 25, 19, 9, 4, 2, 6, 13, 22,...
...     ...                                                ...
9995  59995  [18, 26, 31, 27, 15, 9, 6, 11, 21, 42, 62, 72,...
9996  59996  [27, 43, 68, 86, 83, 58, 27, 12, 12, 24, 40, 5...
9997  59997  [13, 12, 14, 19, 33, 45, 52, 44, 32, 15, 8, 3,...
9998  59998  [19, 27, 40, 43, 38, 23, 15, 16, 26, 30, 30, 2...
9999  59999  [39, 35, 27, 14, 6, 0, 0, 4, 13, 27, 38, 39, 3...

[10000 rows x 2 columns]

In [153]:
test_X = np.stack(test_df['Data'])

In [155]:
test_prediction = model.predict(test_X)

In [158]:
answer_df = pd.DataFrame({
    'file_name' : test_df['Label'],
    'prediction' : test_prediction
})
answer_df.to_csv('M2_Gushin_Ilya_submission.csv', index=False)