In [6]:
path = "D:\\TestJupyter\\data\\Stud_IT_2025_Module_3\\training_datasets"
path_train_data = path + '\\Train_data.pickle'
path_target_data = path + '\\Train_target.pickle'
path_test_data = path + '\\Test_data.pickle'

In [7]:
import pickle
import pandas as pd
import numpy as np

In [9]:
with open(path_train_data, 'rb') as open_train_data:
    raw_train_data = pickle.load(open_train_data)
with open(path_target_data, 'rb') as open_target_data:
    raw_target_data = pickle.load(open_target_data)
with open(path_test_data, 'rb') as open_test_data:
    raw_test_data = pickle.load(open_test_data)

In [10]:
raw_train_data

,positions,atomicNumbers,elements,charge,multiplicity,totalEnergy,gradient,dipoleMoment
id,,,,,,,,
289436,"[[2.7177422046661377, 0.1893724948167801, 1.18...","[3, 9, 15, 9, 9, 9, 9, 9]","[Li, F, P, F, F, F, F, F]",0.0,1.0,-948.513236,"[[0.023912517353892326, -0.0009200238273479044...","[[2.482706308364868], [0.08775771409273148], [..."
172291,"[[-2.809769630432129, 0.4285517930984497, -0.9...","[6, 6, 8, 6, 8, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, ...","[C, C, O, C, O, C, O, H, H, H, H, H, H, C, C, ...",0.0,1.0,-763.972140,"[[-0.034905705600976944, 0.02429979108273983, ...","[[0.865788459777832], [-0.3534996509552002], [..."
16145,"[[-0.6849300861358643, 1.1698198318481445, 0.7...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.612273,"[[-0.02598184533417225, 0.0659920945763588, -0...","[[0.14613808691501617], [0.9436573386192322], ..."
12345,"[[4.158249855041504, 0.05714491382241249, -1.7...","[6, 8, 8, 8, 6, 6, 1, 1, 1, 1, 1, 1, 6, 8, 8, ...","[C, O, O, O, C, C, H, H, H, H, H, H, C, O, O, ...",0.0,1.0,-687.610542,"[[-0.1062416285276413, -0.05160133168101311, 0...","[[0.11332525312900543], [-0.21154789626598358]..."
45824,"[[-0.47792547941207886, 0.718813419342041, -1....","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.626351,"[[-0.01953810453414917, -0.0053415680304169655...","[[-0.7459930777549744], [0.6138357520103455], ..."
...,...,...,...,...,...,...,...,...
119879,"[[1.3755831718444824, 1.8097169399261475, -0.9...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-685.243087,"[[0.04350731149315834, 0.020168600603938103, 0...","[[-1.6112534999847412], [-0.4080508351325989],..."
259178,"[[-1.8912068605422974, -0.7673141956329346, -2...","[9, 15, 9, 9, 9, 9, 9, 6, 6, 8, 6, 8, 8, 9, 1,...","[F, P, F, F, F, F, F, C, C, O, C, O, O, F, H, ...",0.0,1.0,-1832.333954,"[[0.06576894223690033, 0.008227618411183357, 0...","[[2.740854024887085], [1.8966714143753052], [1..."
131932,"[[2.2375781536102295, 1.9658761024475098, -3.9...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-1027.839511,"[[-0.013407240621745586, 0.057573262602090836,...","[[1.6949660778045654], [-1.9628844261169434], ..."
146867,"[[-0.861930251121521, 1.1034585237503052, -0.7...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.598940,"[[-0.018075251951813698, -0.07811354845762253,...","[[-1.0044058561325073], [0.5029338002204895], ..."
121958,"[[0.08739743381738663, -0.4887195825576782, 1....","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.620983,"[[-0.046573419123888016, 0.027960876002907753,...","[[0.5532574653625488], [-0.7378113865852356], ..."

In [11]:
raw_target_data

id
289436   -0.001268
172291   -0.169713
16145    -0.005004
12345     0.044586
45824    -0.019082
            ...
119879   -0.028549
259178   -0.171488
131932   -0.017704
146867    0.008329
121958   -0.013714
Name: atomizationEnergy, Length: 271786, dtype: float64

In [19]:
raw_train_data.info()

<class 'pandas.DataFrame'>
Index: 271786 entries, 289436 to 121958
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   positions      269068 non-null  object
 1   atomicNumbers  269068 non-null  object
 2   elements       269068 non-null  object
 3   charge         269080 non-null  float64
 4   multiplicity   269068 non-null  float64
 5   totalEnergy    269081 non-null  float64
 6   gradient       269068 non-null  object
 7   dipoleMoment   269068 non-null  object
dtypes: float64(3), object(5)
memory usage: 18.7+ MB

In [13]:
raw_target_data.info()

<class 'pandas.Series'>
Index: 271786 entries, 289436 to 121958
Series name: atomizationEnergy
Non-Null Count   Dtype
--------------   -----
271786 non-null  float64
dtypes: float64(1)
memory usage: 4.1 MB

In [18]:
nan_indexes = raw_train_data[raw_train_data.isna().any(axis = 1)].index.tolist()
nan_indexes

[72432,
 109070,
 355367,
 56778,
 113161,
 207144,
 78282,
 26947,
 334569,
 118132,
 77283,
 224349,
 121515,
 17245,
 85746,
 121662,
 98863,
 67506,
 261759,
 59399,
 33122,
 222150,
 307528,
 28862,
 280897,
 56292,
 299969,
 324204,
 11716,
 337467,
 3963,
 178182,
 336724,
 313210,
 99891,
 103662,
 127115,
 88321,
 272588,
 245414,
 67487,
 60006,
 270710,
 250594,
 25624,
 237233,
 2083,
 95638,
 224296,
 161594,
 198047,
 135199,
 255722,
 212732,
 115970,
 277704,
 104103,
 140293,
 333943,
 110890,
 131773,
 36612,
 222559,
 99474,
 131950,
 199256,
 167315,
 222634,
 210951,
 325105,
 241126,
 187249,
 320365,
 76513,
 117591,
 226347,
 177131,
 255000,
 47615,
 231717,
 327773,
 151335,
 96275,
 2044,
 89297,
 175676,
 189208,
 15985,
 342748,
 16809,
 14555,
 253008,
 110968,
 259890,
 198673,
 201233,
 52093,
 314090,
 178154,
 141291,
 53220,
 68632,
 100192,
 167559,
 105256,
 7619,
 272239,
 53538,
 39562,
 56450,
 31049,
 62337,
 41309,
 337554,
 109701,
 211658,
 249297,
 39371,
 319826,
 223892,
 171101,
 90104,
 123320,
 263203,
 292722,
 308446,
 342150,
 323589,
 224123,
 156626,
 5490,
 271299,
 22276,
 206491,
 131081,
 281766,
 109998,
 268711,
 336738,
 211758,
 305288,
 117726,
 170272,
 353283,
 229779,
 234070,
 157101,
 113491,
 35720,
 156764,
 197349,
 126481,
 334666,
 124919,
 195505,
 45349,
 203702,
 4980,
 309870,
 180995,
 341065,
 318909,
 21427,
 14878,
 188786,
 347763,
 438,
 237125,
 361275,
 166594,
 51951,
 324246,
 177847,
 159584,
 329195,
 183718,
 45000,
 317187,
 112825,
 91212,
 296349,
 224948,
 78787,
 181537,
 186434,
 62293,
 122287,
 72457,
 205984,
 40422,
 223774,
 268308,
 113992,
 355028,
 99592,
 192738,
 52278,
 289882,
 71444,
 136848,
 279769,
 70358,
 124100,
 115566,
 248247,
 169718,
 293055,
 340368,
 91383,
 88972,
 342042,
 281291,
 194932,
 361492,
 167263,
 90259,
 182120,
 326805,
 261704,
 5887,
 257729,
 203201,
 291558,
 261941,
 151213,
 271962,
 65489,
 133270,
 114281,
 352383,
 356018,
 99272,
 237606,
 6689,
 131145,
 296998,
 202847,
 60544,
 143782,
 243456,
 13972,
 281279,
 285656,
 237169,
 208596,
 323814,
 35810,
 339287,
 78987,
 288896,
 153295,
 298505,
 90462,
 349185,
 233117,
 81857,
 65278,
 147684,
 182448,
 273002,
 11638,
 255793,
 184646,
 201825,
 121658,
 158616,
 242421,
 241568,
 174377,
 302307,
 310928,
 105376,
 125783,
 359518,
 120959,
 74325,
 66776,
 274852,
 273242,
 222890,
 107025,
 34185,
 238372,
 246270,
 280586,
 73991,
 251546,
 321601,
 81713,
 323579,
 282419,
 290929,
 200497,
 219000,
 79346,
 53728,
 127152,
 332694,
 101714,
 328850,
 266074,
 160468,
 239746,
 302833,
 288015,
 209248,
 8106,
 145410,
 53988,
 52423,
 329730,
 189758,
 16028,
 10989,
 313054,
 132111,
 328018,
 93604,
 242112,
 171828,
 272087,
 324177,
 226043,
 325196,
 212829,
 36689,
 200546,
 149880,
 158451,
 76020,
 201983,
 30494,
 5226,
 34521,
 244510,
 235817,
 210750,
 4031,
 121956,
 291004,
 237940,
 259346,
 222258,
 229140,
 208621,
 323791,
 347767,
 262631,
 17993,
 335541,
 230784,
 142447,
 333742,
 200990,
 240504,
 119320,
 298630,
 289415,
 341397,
 71578,
 212190,
 169120,
 186913,
 106511,
 40802,
 236956,
 133817,
 161701,
 39337,
 3711,
 27191,
 96416,
 264010,
 258149,
 294027,
 320861,
 52863,
 192091,
 341631,
 265430,
 116090,
 300944,
 227469,
 220193,
 218125,
 311433,
 248426,
 93992,
 52555,
 185816,
 78882,
 218111,
 309542,
 151156,
 33145,
 18086,
 135074,
 41433,
 181922,
 181139,
 170664,
 31439,
 331260,
 128469,
 347378,
 143383,
 26725,
 291508,
 161615,
 261845,
 54280,
 71161,
 266188,
 92905,
 335345,
 325649,
 115275,
 156028,
 21040,
 54393,
 124392,
 35815,
 3289,
 342100,
 303131,
 272121,
 334498,
 60304,
 99577,
 298383,
 53361,
 112811,
 63496,
 303732,
 34109,
 315171,
 69791,
 155401,
 252600,
 22253,
 256598,
 187999,
 269772,
 79969,
 69485,
 84334,
 267644,
 160421,
 54742,
 235804,
 171260,
 226927,
 357568,
 226662,
 226104,
 227415,
 206867,
 12762,
 230436,
 62553,
 127485,
 276046,
 164312,
 279030,
 64468,
 238990,
 167597,
 5866,
 115841,
 218406,
 233963,
 253909,
 136114,
 180731,
 238707,
 23532,
 76679,
 109468,
 317064,
 345902,
 128095,
 17974,
 240757,
 112899,
 154362,
 193847,
 185838,
 343653,
 113571,
 123798,
 228741,
 50346,
 208144,
 115452,
 124948,
 162790,
 165025,
 154547,
 107570,
 262452,
 176988,
 89009,
 329000,
 49071,
 47906,
 313950,
 229616,
 146345,
 156991,
 208108,
 119003,
 150178,
 113608,
 257566,
 74306,
 245281,
 166740,
 347959,
 42639,
 346979,
 294125,
 72278,
 128599,
 91927,
 166196,
 295165,
 143768,
 138977,
 335277,
 273884,
 313383,
 322369,
 217166,
 210781,
 242589,
 53607,
 296114,
 244763,
 100035,
 11035,
 105122,
 272140,
 274436,
 346247,
 287797,
 280521,
 326685,
 293453,
 353372,
 293815,
 37867,
 115046,
 331520,
 149482,
 253513,
 332652,
 87215,
 192969,
 199211,
 119737,
 113337,
 195369,
 362053,
 347189,
 262252,
 158130,
 73813,
 262073,
 219615,
 294666,
 92763,
 34331,
 94165,
 349439,
 292971,
 95584,
 246706,
 336200,
 293950,
 251835,
 258119,
 215372,
 331611,
 47855,
 121356,
 87963,
 34624,
 75106,
 109349,
 207035,
 15899,
 61440,
 163305,
 147196,
 226475,
 279517,
 183562,
 110296,
 71604,
 73220,
 227611,
 120839,
 116210,
 53179,
 334606,
 352742,
 242868,
 56487,
 288099,
 168058,
 207809,
 13668,
 109422,
 64516,
 211702,
 192517,
 326599,
 334277,
 221278,
 85655,
 93599,
 221089,
 193560,
 263857,
 283110,
 7434,
 636,
 313304,
 257843,
 153661,
 75477,
 349951,
 56428,
 29516,
 12102,
 300267,
 356782,
 85487,
 335908,
 99935,
 139896,
 239688,
 221728,
 312184,
 203647,
 170481,
 120610,
 120191,
 99833,
 129624,
 326168,
 273819,
 303340,
 349387,
 188465,
 221563,
 111510,
 184692,
 95048,
 9960,
 1290,
 267914,
 89327,
 74701,
 74817,
 137247,
 117343,
 74907,
 121100,
 59173,
 347254,
 333899,
 229580,
 274290,
 98839,
 42117,
 62451,
 228079,
 114844,
 112561,
 66313,
 320418,
 244197,
 162305,
 217936,
 299400,
 89222,
 97079,
 139692,
 232471,
 173567,
 217404,
 140069,
 341824,
 343223,
 46874,
 330190,
 129635,
 273682,
 144259,
 59297,
 76220,
 127522,
 315846,
 216167,
 65598,
 274315,
 166766,
 23265,
 175408,
 118989,
 15757,
 298529,
 81703,
 295441,
 50340,
 104644,
 231406,
 177870,
 309063,
 21765,
 69249,
 319058,
 220271,
 183424,
 260495,
 323046,
 290052,
 226196,
 347204,
 66734,
 205312,
 96910,
 216587,
 354200,
 281083,
 108908,
 339885,
 332119,
 177167,
 68419,
 345929,
 206371,
 41771,
 338256,
 140835,
 76339,
 256241,
 219902,
 62686,
 235215,
 327309,
 279718,
 193559,
 352080,
 104863,
 78411,
 70080,
 30200,
 274547,
 40788,
 331101,
 338948,
 153563,
 286448,
 86799,
 57975,
 248629,
 79782,
 160061,
 202095,
 264725,
 351978,
 64178,
 359953,
 226207,
 280885,
 294480,
 271745,
 47844,
 131462,
 258461,
 225715,
 279862,
 50320,
 267706,
 326051,
 151198,
 78336,
 48409,
 333837,
 292516,
 288934,
 76234,
 168946,
 9928,
 224623,
 114514,
 138685,
 175792,
 279898,
 70058,
 215615,
 58800,
 75212,
 58984,
 7215,
 299843,
 128116,
 313790,
 299932,
 357341,
 332075,
 250509,
 115207,
 289775,
 241869,
 340425,
 8305,
 87511,
 236065,
 320548,
 38509,
 70758,
 333084,
 115272,
 5766,
 269314,
 164745,
 271163,
 173485,
 76304,
 148149,
 88716,
 244616,
 172571,
 92620,
 2058,
 18977,
 99967,
 93880,
 129464,
 250568,
 141354,
 279047,
 205094,
 267809,
 35069,
 261482,
 352900,
 358810,
 296373,
 226055,
 220520,
 110844,
 109329,
 115618,
 249427,
 307950,
 251343,
 148948,
 183154,
 48946,
 19293,
 215644,
 248222,
 161841,
 221034,
 136159,
 337920,
 124879,
 347116,
 49523,
 322376,
 14451,
 112773,
 111748,
 205290,
 90074,
 60281,
 213584,
 353307,
 291896,
 270572,
 275652,
 97938,
 259119,
 45486,
 211288,
 90573,
 328344,
 233051,
 232951,
 53152,
 291413,
 349155,
 351004,
 91431,
 26837,
 71494,
 198242,
 346829,
 60922,
 357390,
 204369,
 277402,
 94080,
 292223,
 85995,
 225982,
 181468,
 286280,
 225498,
 300540,
 129766,
 307368,
 290442,
 54721,
 273272,
 211120,
 173155,
 166381,
 299222,
 251077,
 66569,
 223128,
 224707,
 209335,
 129548,
 52074,
 81936,
 91786,
 244979,
 14544,
 1851,
 100981,
 231023,
 286507,
 35529,
 328014,
 61343,
 2533,
 264984,
 249641,
 103130,
 182838,
 138586,
 74638,
 271244,
 274576,
 227287,
 95559,
 314521,
 135485,
 203738,
 291030,
 136092,
 19363,
 264017,
 35227,
 14014,
 153632,
 112703,
 19172,
 107410,
 52326,
 309386,
 310530,
 210471,
 286019,
 351682,
 326073,
 36084,
 314307,
 330902,
 224455,
 243573,
 68563,
 143027,
 260216,
 32469,
 271661,
 136623,
 318006,
 151841,
 61515,
 211412,
 166172,
 337404,
 245322,
 84870,
 337153,
 225694,
 40328,
 218916,
 150778,
 325130,
 316640,
 223367,
 230626,
 ...]

In [25]:
dropped_train = raw_train_data.dropna()

In [19]:
dropped_target = raw_target_data.drop(nan_indexes)

In [20]:
dropped_target.info()

<class 'pandas.Series'>
Index: 269068 entries, 289436 to 121958
Series name: atomizationEnergy
Non-Null Count   Dtype
--------------   -----
269068 non-null  float64
dtypes: float64(1)
memory usage: 4.1 MB

In [26]:
dropped_train.info()

<class 'pandas.DataFrame'>
Index: 269068 entries, 289436 to 121958
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   positions      269068 non-null  object
 1   atomicNumbers  269068 non-null  object
 2   elements       269068 non-null  object
 3   charge         269068 non-null  float64
 4   multiplicity   269068 non-null  float64
 5   totalEnergy    269068 non-null  float64
 6   gradient       269068 non-null  object
 7   dipoleMoment   269068 non-null  object
dtypes: float64(3), object(5)
memory usage: 18.5+ MB

In [43]:
ravel_df = dropped_train

In [44]:
ravel_df

,positions,atomicNumbers,elements,charge,multiplicity,totalEnergy,gradient,dipoleMoment
id,,,,,,,,
289436,"[[2.7177422046661377, 0.1893724948167801, 1.18...","[3, 9, 15, 9, 9, 9, 9, 9]","[Li, F, P, F, F, F, F, F]",0.0,1.0,-948.513236,"[[0.023912517353892326, -0.0009200238273479044...","[[2.482706308364868], [0.08775771409273148], [..."
172291,"[[-2.809769630432129, 0.4285517930984497, -0.9...","[6, 6, 8, 6, 8, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, ...","[C, C, O, C, O, C, O, H, H, H, H, H, H, C, C, ...",0.0,1.0,-763.972140,"[[-0.034905705600976944, 0.02429979108273983, ...","[[0.865788459777832], [-0.3534996509552002], [..."
16145,"[[-0.6849300861358643, 1.1698198318481445, 0.7...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.612273,"[[-0.02598184533417225, 0.0659920945763588, -0...","[[0.14613808691501617], [0.9436573386192322], ..."
12345,"[[4.158249855041504, 0.05714491382241249, -1.7...","[6, 8, 8, 8, 6, 6, 1, 1, 1, 1, 1, 1, 6, 8, 8, ...","[C, O, O, O, C, C, H, H, H, H, H, H, C, O, O, ...",0.0,1.0,-687.610542,"[[-0.1062416285276413, -0.05160133168101311, 0...","[[0.11332525312900543], [-0.21154789626598358]..."
45824,"[[-0.47792547941207886, 0.718813419342041, -1....","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.626351,"[[-0.01953810453414917, -0.0053415680304169655...","[[-0.7459930777549744], [0.6138357520103455], ..."
...,...,...,...,...,...,...,...,...
119879,"[[1.3755831718444824, 1.8097169399261475, -0.9...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-685.243087,"[[0.04350731149315834, 0.020168600603938103, 0...","[[-1.6112534999847412], [-0.4080508351325989],..."
259178,"[[-1.8912068605422974, -0.7673141956329346, -2...","[9, 15, 9, 9, 9, 9, 9, 6, 6, 8, 6, 8, 8, 9, 1,...","[F, P, F, F, F, F, F, C, C, O, C, O, O, F, H, ...",0.0,1.0,-1832.333954,"[[0.06576894223690033, 0.008227618411183357, 0...","[[2.740854024887085], [1.8966714143753052], [1..."
131932,"[[2.2375781536102295, 1.9658761024475098, -3.9...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-1027.839511,"[[-0.013407240621745586, 0.057573262602090836,...","[[1.6949660778045654], [-1.9628844261169434], ..."
146867,"[[-0.861930251121521, 1.1034585237503052, -0.7...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.598940,"[[-0.018075251951813698, -0.07811354845762253,...","[[-1.0044058561325073], [0.5029338002204895], ..."
121958,"[[0.08739743381738663, -0.4887195825576782, 1....","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.620983,"[[-0.046573419123888016, 0.027960876002907753,...","[[0.5532574653625488], [-0.7378113865852356], ..."

In [73]:
ravel_df['positions'] = ravel_df['positions'].apply(lambda i: i.ravel())
ravel_df['gradient'] = ravel_df['gradient'].apply(lambda i: i.ravel())
ravel_df['dipoleMoment'] = ravel_df['dipoleMoment'].apply(lambda i: i.ravel())

In [79]:
X = ravel_df
y = dropped_target

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [84]:
X_train

,positions,atomicNumbers,elements,charge,multiplicity,totalEnergy,gradient,dipoleMoment
id,,,,,,,,
281063,"[-0.05609479174017906, 2.900641679763794, 1.04...","[6, 6, 8, 6, 8, 8, 1, 1, 6, 6, 8, 6, 8, 8, 1, 1]","[C, C, O, C, O, O, H, H, C, C, O, C, O, O, H, H]",0.0,1.0,-682.746752,"[0.012927830219268799, 0.025442782789468765, 0...","[0.08382778614759445, 1.6511467695236206, 0.65..."
140544,"[0.06919373571872711, 1.5686135292053223, -0.2...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1]","[C, O, C, O, C, H, H, O, H, H]",0.0,1.0,-342.622460,"[-0.0030106762424111366, 0.030155885964632034,...","[0.3025994896888733, 1.1212025880813599, 0.323..."
148339,"[-3.0675082206726074, -3.7520878314971924, -0....","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-1713.078166,"[0.0716153234243393, -0.11138030141592026, 0.0...","[1.11066472530365, 2.3592453002929688, -2.6047..."
254156,"[1.9241405725479126, -0.009226176887750626, -2...","[6, 6, 8, 6, 8, 8, 1, 1, 6, 6, 8, 6, 8, 8, 1, ...","[C, C, O, C, O, O, H, H, C, C, O, C, O, O, H, ...",0.0,1.0,-1365.495747,"[0.013670776970684528, -0.11125116795301437, -...","[-1.4053165912628174, -0.5168069005012512, -0...."
276225,"[0.7742071151733398, -3.1158852577209473, -0.7...","[9, 15, 9, 9, 9, 9, 9, 6, 6, 8, 6, 8, 8, 1, 1,...","[F, P, F, F, F, F, F, C, C, O, C, O, O, H, H, ...",0.0,1.0,-1291.115271,"[0.024707641452550888, -0.009173580445349216, ...","[-0.11392133682966232, 3.1750097274780273, 1.2..."
...,...,...,...,...,...,...,...,...
17167,"[-1.9374595880508423, 1.0720667839050293, -2.6...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-685.243016,"[-0.030478838831186295, -0.025508727878332138,...","[0.3401167392730713, -0.5174998641014099, -1.8..."
345196,"[0.0, -0.0, -2.8890326023101807, 0.0, 0.0, 2.8...","[3, 3]","[Li, Li]",2.0,1.0,-14.484970,"[-9.317069317131622e-32, 9.317069317131622e-32...","[0.0, 0.0, 4.700037593548343e-16]"
350300,"[-1.4012303352355957, -2.1450153168427045e-17,...","[3, 3]","[Li, Li]",2.0,1.0,-14.390619,"[0.0657590925693512, 1.0066457182525326e-18, -...","[0.0, -1.63065311030037e-32, 0.0]"
94679,"[-1.480996012687683, 1.0131430625915527, 0.897...","[6, 8, 6, 8, 6, 8, 9, 1, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, O, F, H, H, H, C, O, C, O, C, ...",0.0,1.0,-883.782356,"[0.006405757274478674, -0.08379901945590973, -...","[-0.5359984040260315, 0.5711998343467712, 0.18..."
201493,"[5.069007396697998, -1.8343764543533325, -1.10...","[6, 8, 6, 8, 6, 1, 1, 8, 1, 1, 6, 8, 6, 8, 6, ...","[C, O, C, O, C, H, H, O, H, H, C, O, C, O, C, ...",0.0,1.0,-1027.852371,"[-0.04559361934661865, 0.09567542374134064, -0...","[2.0673210620880127, -1.639555811882019, -0.79..."

In [82]:
from sklearn.preprocessing import StandardScaler

In [83]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: setting an array element with a sequence.